# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:08:38+00:00



import argparse
import json
import os
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity
from fastapi import Header, Query

from models import (
    AadharNumberRequestPayload,
    AadharOtpGenerateRequestPayLoad,
    AuthAccountAadhaarBioRequest,
    AuthAccountAadhaarOTPRequest,
    AuthAccountMobileOTPRequest,
    AuthAccountWithDemographicsRequest,
    AuthInitRequest,
    AuthMobileOTPRequest,
    AuthWithMobileTxnAndUserData,
    AuthWithPasswordRequest,
    CreateAccountByVerifiedMobileRequest,
    CreateAccountJwtResponse,
    CreateAccountWithAadhaarOtp,
    CreateAccountWithPreVerifiedAadhaar,
    CreateHealthIdOptRequest,
    CreateHidBiometricRequest,
    CreateHIdDemoAuthRequest,
    CreateHidMobileRequest,
    CreateHidNotifyBenefitRequest,
    GenerateMobileOTPForTxnRequest,
    GenerateMobileOTPRequest,
    HealthFacilityAuthenticationRequest,
    HealthFacilityChangedPasswordRequest,
    HealthFacilityPasswordRequest,
    HidBenefitDelinkRequestPayload,
    HidBenefitLinkedRequestPayload,
    HidBenefitLinkedResponsePayload,
    HidBenefitNameSearchRequest,
    HidBenefitRequestPayload,
    HidChangePasswordRequestPayload,
    HidOtpRequestPaylaod,
    HidStatusRequestPayload,
    HidUpdateAccountRequest,
    HidUpdateMobiletRequest,
    JwtRequest,
    JwtResponse,
    MobileVerificationToken,
    ResendOTPRequest,
    RetrieveHealthIdPayloadResponse,
    RetriveHealthIdMobilePayLoad,
    SearchByHealthIdRequest,
    SearchByMobileRequest,
    SearchResponseSingle,
    TagRequest,
    TxnResponse,
    UpdateAccountRequest,
    UserDTO,
    V1HaLgdDistrictsGetResponse,
    V1HaLgdStatesGetResponse,
    V1HaTagsDeleteResponse,
    V1HaTagsGetResponse,
    V1HaTagsPostResponse,
    V1HidBenefitSearchAadhaarPostResponse,
    V1HidBenefitSearchHealthIdNumberPostResponse,
    V1RegistrationAadhaarSearchAadharPostResponse,
    V1SearchExistsByHealthIdPostResponse,
    ValidateTokenRequest,
    VerifyAadhaarOtp,
    VerifyAadhaarWithBio,
    VerifyMobileRequest,
)

app = MCPProxy(
    contact={'name': 'National Health Authority', 'url': 'https://ndhm.gov.in/'},
    description='It is important to standardize the process of identification of an individual across healthcare providers, to ensure that the created medical records are issued to the right individual or accessed by a Health Information User through appropriate consent. \nIn order to issue a Health ID to an individual, one only needs basic demographic details like Name, Year of Birth, Gender. In addition, citizens should be able to update contact information easily.',
    title='Health ID Service',
    version='1.0',
    servers=[{'url': 'https://healthidsbx.ndhm.gov.in/api'}],
)


@app.post(
    '/v1/account/aadhaar/generateOTP',
    description=""" Generate Aadhaar OTP on registrered for link account with aadhar number """,
    tags=[
        'kyc_operations',
        'otp_generation_service',
        'aadhaar_otp_services',
        'authentication_process',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def generatere_kyc_aadhar_o_t_p_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    x__token: str = Header(..., alias='X-Token'),
):
    """
    Generate Aadhaar OTP on registrered for link account with aadhar number
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/account/aadhaar/verifyOTP',
    description=""" Verify Aadhaar OTP to complete KYC/re-KYC verification """,
    tags=[
        'kyc_operations',
        'otp_verification_management',
        'aadhaar_otp_services',
        'aadhaar_identity_verification',
        'authentication_process',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def verify_aadhar_o_t_p_only_using_p_o_s_t_1(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    x__token: str = Header(..., alias='X-Token'),
    body: VerifyAadhaarOtp = ...,
):
    """
    Verify Aadhaar OTP to complete KYC/re-KYC verification.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/account/benefits',
    tags=['user_information_retrieval', 'health_id_search_management'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def get_benefits_using_g_e_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    x__token: str = Header(..., alias='X-Token'),
):
    """
    Get List of Benefits associated with HealthID.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/account/change/passwd/byAadhaar',
    description=""" Change password via Aadhar for heath id. """,
    tags=['password_management', 'aadhaar_otp_services', 'authentication_process'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def change_password_via_aadhar_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    x__token: str = Header(..., alias='X-Token'),
    body: HidOtpRequestPaylaod = ...,
):
    """
    Change password via Aadhar for heath id.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/account/change/passwd/byMobile',
    description=""" Change password via mobile for heath id. """,
    tags=['password_management', 'authentication_process', 'mobile_otp_services'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def change_password_via_mobile_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    x__token: str = Header(..., alias='X-Token'),
    body: HidOtpRequestPaylaod = ...,
):
    """
    Change password via mobile for heath id.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/account/change/passwd/generateAadhaarOTP',
    description=""" Generate Aadhaar OTP on registrered mobile number. """,
    tags=[
        'kyc_operations',
        'otp_generation_service',
        'aadhaar_otp_services',
        'authentication_process',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def generate_aadhar_o_t_p_using_g_e_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    x__token: str = Header(..., alias='X-Token'),
):
    """
    Generate Aadhaar OTP on registrered mobile number.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/account/change/passwd/generateMobileOTP',
    description=""" Generate Mobile OTP to start registration. """,
    tags=[
        'otp_generation_service',
        'otp_verification_management',
        'mobile_otp_services',
        'authentication_process',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def generate_mobile_o_t_p_using_g_e_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    x__token: str = Header(..., alias='X-Token'),
):
    """
    Generate Mobile OTP to start registration.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/account/change/password',
    description=""" Change password via password for heath id. """,
    tags=['password_management', 'authentication_process'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def change_password_via_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    x__token: str = Header(..., alias='X-Token'),
    body: HidChangePasswordRequestPayload = ...,
):
    """
    Change password via password for heath id.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/account/getCard',
    tags=['health_id_card_generation'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def generate_card_using_g_e_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    x__token: str = Header(..., alias='X-Token'),
):
    """
    Generate Health ID card in PDF format
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/account/getPngCard',
    tags=['health_id_card_generation'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def generate_png_card_using_g_e_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    x__token: str = Header(..., alias='X-Token'),
):
    """
    Generate Health ID card PNG
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/account/getSvgCard',
    tags=['health_id_card_generation'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def generate_svg_card_using_g_e_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    x__token: str = Header(..., alias='X-Token'),
):
    """
    Generate Health ID card SVG
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/account/profile',
    tags=['account_management'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def delete_account_using_d_e_l_e_t_e(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    x__token: str = Header(..., alias='X-Token'),
):
    """
    Delete account
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/account/profile',
    tags=['account_management', 'user_information_retrieval'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def get_account_information_using_g_e_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    x__token: str = Header(..., alias='X-Token'),
):
    """
    Get account information.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/account/profile',
    tags=['account_management'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def update_account_information_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    x__token: str = Header(..., alias='X-Token'),
    body: UpdateAccountRequest = ...,
):
    """
    Update account information
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/account/qrCode',
    tags=['account_management', 'health_id_card_generation'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def get_qr_code_using_g_e_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    x__token: str = Header(..., alias='X-Token'),
):
    """
    Get Quick Response code in PNG format for this account.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/account/token',
    tags=['authentication_process'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def validate_token_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: ValidateTokenRequest = ...,
):
    """
    Validate auth token
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/auth/authPassword',
    tags=['authentication_process', 'kyc_operations'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def authenticate_with_password_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: JwtRequest = ...,
):
    """
    Authenticate using Health ID number / Health ID and password
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/auth/authWithMobile',
    tags=[
        'kyc_operations',
        'authentication_process',
        'otp_generation_service',
        'mobile_otp_services',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def authenticate_user_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: AuthMobileOTPRequest = ...,
):
    """
    Authenticate request to generate Mobile OTP using Health ID number / Health ID
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/auth/authWithMobileToken',
    tags=[
        'authentication_process',
        'mobile_otp_services',
        'user_information_retrieval',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def auth_with_mobile_token_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: AuthWithMobileTxnAndUserData = ...,
):
    """
    Authenticate using verified Mobile Number and user data
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/auth/cert',
    tags=['authentication_process'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def cert_using_g_e_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language')
):
    """
    Auth token public key.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/auth/confirmWithAadhaarBio',
    tags=['authentication_process', 'aadhaar_identity_verification'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def confirm_with_aadhaar_bio_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: AuthAccountAadhaarBioRequest = ...,
):
    """
    Authentication with Aadhaar Biometric based auth transaction.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/auth/confirmWithAadhaarOtp',
    tags=[
        'kyc_operations',
        'authentication_process',
        'aadhaar_otp_services',
        'aadhaar_identity_verification',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def confirm_with_aadhaar_otp_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: AuthAccountAadhaarOTPRequest = ...,
):
    """
    Authentication with Aadhaar OTP based auth transaction.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/auth/confirmWithDemographics',
    tags=['authentication_process', 'aadhaar_identity_verification'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def confirm_with_demographics_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: AuthAccountWithDemographicsRequest = ...,
):
    """
    Authenticate using demographic data of user.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/auth/confirmWithMobileOTP',
    tags=[
        'authentication_process',
        'mobile_otp_services',
        'otp_verification_management',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def confirm_with_mobile_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: AuthAccountMobileOTPRequest = ...,
):
    """
    Authentication with Mobile OTP based auth transaction.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/auth/confirmWithPassword',
    tags=['authentication_process', 'password_management'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def auth_account_password_request_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: AuthWithPasswordRequest = ...,
):
    """
    Authentication with PASSWORD based auth transaction.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/auth/init',
    tags=['authentication_process', 'health_id_search_management'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def initiate_auth_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: AuthInitRequest = ...,
):
    """
    Initiate authentication process for given Health ID
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/auth/resendAuthOTP',
    tags=[
        'kyc_operations',
        'authentication_process',
        'otp_generation_service',
        'otp_verification_management',
        'aadhaar_otp_services',
        'mobile_otp_services',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def resend_auth_mobile_o_t_p_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: ResendOTPRequest = ...,
):
    """
    Resend Aadhaar/Mobile OTP for Authentication Transaction.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/forgot/healthId/aadhaar',
    description=""" Verify aadhar OTP sent as part of forgetHealth id. """,
    tags=[
        'kyc_operations',
        'otp_verification_management',
        'aadhaar_otp_services',
        'authentication_process',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def retrieval_health_id_by_aadhar_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: AuthAccountAadhaarOTPRequest = ...,
):
    """
    Verify aadhar OTP sent as part of forgetHealth id.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/forgot/healthId/aadhaar/generateOtp',
    description=""" Generate Aadhaar OTP on registrered mobile number """,
    tags=[
        'kyc_operations',
        'otp_generation_service',
        'aadhaar_otp_services',
        'authentication_process',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def generate_aadhar_o_t_p_using_p_o_s_t_1(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: AadharOtpGenerateRequestPayLoad = ...,
):
    """
    Generate Aadhaar OTP on registrered mobile number
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/forgot/healthId/mobile',
    description=""" Verify Mobile OTP sent as  part of forgetHealth id. """,
    tags=[
        'otp_verification_management',
        'mobile_otp_services',
        'authentication_process',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def retrieval_health_id_by_mobile_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: RetriveHealthIdMobilePayLoad = ...,
):
    """
    Verify Mobile OTP sent as  part of forgetHealth id.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/forgot/healthId/mobile/generateOtp',
    description=""" Generate Mobile OTP to start registration transaction. """,
    tags=[
        'otp_generation_service',
        'mobile_otp_services',
        'otp_verification_management',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def generate_mobile_o_t_p_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: GenerateMobileOTPRequest = ...,
):
    """
    Generate Mobile OTP to start registration
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/ha/lgd/districts',
    tags=['state_district_information'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def get_districts_in_state_using_g_e_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    state_code: str = Query(..., alias='stateCode'),
):
    """
    Get a list of districts in a given  State as per LGD.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/ha/lgd/states',
    tags=['state_district_information'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def get_states_using_g_e_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language')
):
    """
    Get a list of states as per LGD.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/ha/tags',
    tags=['tagging_operations', 'account_management'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def delete_tag_using_d_e_l_e_t_e(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language')
):
    """
    Delete tag against HealthId.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/ha/tags',
    tags=['tagging_operations', 'health_id_search_management'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def get_tags_using_g_e_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    x__token: str = Header(..., alias='X-Token'),
):
    """
    Get list of Tags against HealthID.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/ha/tags',
    tags=['tagging_operations'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def add_tag_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: TagRequest = ...,
):
    """
    Add tag against HealthId.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/health/facility/authenticate',
    description=""" Generate token for heath facility id. """,
    tags=['facility_authentication_management', 'authentication_process'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def authenticate_health_facility_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: HealthFacilityAuthenticationRequest = ...,
):
    """
    Generate token for heath facility id.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/health/facility/change/password',
    description=""" Change password for heath facility id. """,
    tags=['password_management', 'facility_authentication_management'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def change_password_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: HealthFacilityChangedPasswordRequest = ...,
):
    """
    Change password for heath facility id.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/health/facility/createHealthIdWithPreVerified',
    tags=['health_id_card_generation', 'kyc_operations'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def create_aadhaar_account_using_p_o_s_t_1(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: CreateAccountWithPreVerifiedAadhaar = ...,
):
    """
    Generate Health ID card SVG
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/health/facility/generate/password',
    description=""" Generates password for heath facility id. """,
    tags=['password_management', 'facility_authentication_management'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def generate_password_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: HealthFacilityPasswordRequest = ...,
):
    """
    Generates password for heath facility id.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/health/facility/generateOtp',
    description=""" Generate health facility OTP on registrered mobile number """,
    tags=[
        'kyc_operations',
        'otp_generation_service',
        'mobile_otp_services',
        'aadhaar_otp_services',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def generate_facility_o_t_p_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    x__token: str = Header(..., alias='X-Token'),
    body: AadharOtpGenerateRequestPayLoad = ...,
):
    """
    Generate health hacility OTP on registrered mobile number
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/health/facility/getSvgCard',
    tags=['health_id_card_generation'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def generate_svg_card_using_g_e_t_1(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    health__i_d: str = Header(..., alias='Health-ID'),
    x__token: str = Header(..., alias='X-Token'),
):
    """
    generateSvgCard
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/health/facility/reset/password',
    description=""" Reset password for heath facility id. """,
    tags=['password_management', 'facility_authentication_management'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def reset_password_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: HealthFacilityPasswordRequest = ...,
):
    """
    Reset password for heath facility id.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/hid/benefit/aadhaar/generateOtp',
    description=""" Generate Aadhaar OTP on registrered mobile number """,
    tags=[
        'kyc_operations',
        'otp_generation_service',
        'aadhaar_otp_services',
        'authentication_process',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def generate_aadhar_o_t_p_using_p_o_s_t_2(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: AadharOtpGenerateRequestPayLoad = ...,
):
    """
    Generate Aadhaar OTP on registrered mobile number
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/hid/benefit/aadhaar/verifyAadharOtp',
    description=""" Create health id using Aadhaar number opt """,
    tags=[
        'kyc_operations',
        'otp_generation_service',
        'otp_verification_management',
        'aadhaar_otp_services',
        'health_id_card_generation',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def verify_aadhar_otp_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: CreateHealthIdOptRequest = ...,
):
    """
    Create health id using Aadhaar Number Otp.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/hid/benefit/aadhaar/verifyBio',
    description=""" Create health id using Biometric Authentication. """,
    tags=[
        'health_id_card_generation',
        'authentication_process',
        'aadhaar_identity_verification',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def verify_bio_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: CreateHidBiometricRequest = ...,
):
    """
    Create health id using Biometric Authentication.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/hid/benefit/createHealthId/demo/auth',
    description=""" Create health id using Aadhaar Demo Auth. """,
    tags=[
        'health_id_card_generation',
        'aadhaar_identity_verification',
        'otp_verification_management',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def create_health_id_by_demo_auth_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: CreateHIdDemoAuthRequest = ...,
):
    """
    Create health id using Aadhaar Demo Auth.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/hid/benefit/delink',
    description=""" De-Linked with hid. """,
    tags=['account_management'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def delink_hid_benefit_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: HidBenefitDelinkRequestPayload = ...,
):
    """
    De-Linked with hid.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/hid/benefit/link',
    description=""" Linked with hid. """,
    tags=['health_id_search_management', 'aadhaar_identity_verification'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def link_hid_benefit_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: HidBenefitLinkedRequestPayload = ...,
):
    """
    Linked with hid.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/hid/benefit/mobile/createHealthId',
    description=""" Create health id using mobile Authentication. """,
    tags=[
        'kyc_operations',
        'authentication_process',
        'otp_generation_service',
        'otp_verification_management',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def create_health_id_by_mobile_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: CreateHidMobileRequest = ...,
):
    """
    Create health id using mobile Authentication.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/hid/benefit/mobile/generateOtp',
    description=""" Generate mobile OTP on registrered mobile number """,
    tags=[
        'otp_generation_service',
        'mobile_otp_services',
        'authentication_process',
        'otp_verification_management',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def generate_mobile_otp_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: GenerateMobileOTPRequest = ...,
):
    """
    Generate mobile OTP on registrered mobile number
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/hid/benefit/notify/benefit',
    description=""" Create health id using notify Benefit. """,
    tags=[
        'health_id_card_generation',
        'otp_verification_management',
        'user_information_retrieval',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def notify_benefit_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: CreateHidNotifyBenefitRequest = ...,
):
    """
    Create health id using notify Benefit.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/hid/benefit/search/aadhaar',
    description=""" Search health id number using aadhar or aadhar token. """,
    tags=[
        'kyc_operations',
        'health_id_search_management',
        'user_information_retrieval',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def find_by_aadhar_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: AadharNumberRequestPayload = ...,
):
    """
    Search health id number using aadhar or aadhar token.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/hid/benefit/search/healthIdNumber',
    description=""" Search benefit using health id number """,
    tags=['health_id_search_management', 'user_information_retrieval'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def find_by_health_id_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: HidBenefitNameSearchRequest = ...,
):
    """
    Search benefit using health id number.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/hid/benefit/update/mobile',
    tags=['account_management'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def update_mobile_information_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: HidUpdateMobiletRequest = ...,
):
    """
    Update mobile number for account.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/hid/benefit/update/profile',
    tags=['account_management'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def update_account_information_using_p_o_s_t_1(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: HidUpdateAccountRequest = ...,
):
    """
    Update account information
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/hid/benefit/update/status',
    description=""" Update health id status. """,
    tags=['account_management'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def update_status_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: HidStatusRequestPayload = ...,
):
    """
    Update health id status .
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/registration/aadhaar/createHealthIdWithAadhaarOtp',
    description=""" Verify Aadhar OTP received on registrered mobile number """,
    tags=[
        'kyc_operations',
        'otp_verification_management',
        'aadhaar_otp_services',
        'authentication_process',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def verify_aadhar_o_t_p_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: CreateAccountWithAadhaarOtp = ...,
):
    """
    Verify Aadhaar OTP on registrered mobile number to create Health ID.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/registration/aadhaar/createHealthIdWithPreVerified',
    description=""" Create Health ID using pre-verified Aadhaar & Mobile. """,
    tags=[
        'kyc_operations',
        'health_id_card_generation',
        'otp_verification_management',
        'aadhaar_identity_verification',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def create_aadhaar_account_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: CreateAccountWithPreVerifiedAadhaar = ...,
):
    """
    Create Health ID using pre-verified Aadhaar & Mobile.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/registration/aadhaar/generateMobileOTP',
    description=""" Generate Mobile OTP to verify mobile number. """,
    tags=[
        'otp_generation_service',
        'otp_verification_management',
        'mobile_otp_services',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def generate_mobile_o_t_p_for_txn_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: GenerateMobileOTPForTxnRequest = ...,
):
    """
    Generate Mobile OTP for verification.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/registration/aadhaar/generateOtp',
    description=""" Generate Aadhaar OTP on registrered mobile number """,
    tags=[
        'kyc_operations',
        'otp_generation_service',
        'aadhaar_otp_services',
        'authentication_process',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def generate_aadhar_o_t_p_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: AadharOtpGenerateRequestPayLoad = ...,
):
    """
    Generate Aadhaar OTP on registrered mobile number
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/registration/aadhaar/resendAadhaarOtp',
    description=""" Resend Aadhar OTP on registrered mobile number """,
    tags=[
        'kyc_operations',
        'aadhaar_otp_services',
        'otp_verification_management',
        'mobile_otp_services',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def resend_aadhar_o_t_p_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: ResendOTPRequest = ...,
):
    """
    Resend Aadhaar OTP on registrered mobile number to create Health ID.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/registration/aadhaar/search/aadhar',
    description=""" Search health id number using aadhar. """,
    tags=[
        'health_id_search_management',
        'aadhaar_identity_verification',
        'user_information_retrieval',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def get_health_id_numbers_by_aadhar_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: AadharNumberRequestPayload = ...,
):
    """
    Search health id number using aadhar.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/registration/aadhaar/verifyBio',
    description=""" Verify Aadhaar using biometrics """,
    tags=['kyc_operations', 'authentication_process', 'aadhaar_identity_verification'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def verify_aadhar_bio_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: VerifyAadhaarWithBio = ...,
):
    """
    Verify Aadhaar using biometrics.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/registration/aadhaar/verifyMobileOTP',
    description=""" Verify Mobile OTP in an existing transaction. """,
    tags=[
        'otp_verification_management',
        'mobile_otp_services',
        'authentication_process',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def verify_mobile_o_t_p_for_txn_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: VerifyMobileRequest = ...,
):
    """
    Verify Mobile OTP in an existing transaction.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/registration/aadhaar/verifyOTP',
    description=""" Verify Aadhaar OTP received on registrered mobile number """,
    tags=[
        'kyc_operations',
        'otp_verification_management',
        'aadhaar_otp_services',
        'aadhaar_identity_verification',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def verify_aadhar_o_t_p_only_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: VerifyAadhaarOtp = ...,
):
    """
    Verify Aadhaar OTP and continue for mobile verification.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/registration/mobile/createHealthId',
    tags=[
        'kyc_operations',
        'health_id_card_generation',
        'otp_verification_management',
        'mobile_otp_services',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def verify_user_via_mobile_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: CreateAccountByVerifiedMobileRequest = ...,
):
    """
    Create Health ID with verified mobile token
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/registration/mobile/generateOtp',
    description=""" Generate Mobile OTP to start registration transaction. """,
    tags=[
        'kyc_operations',
        'otp_generation_service',
        'otp_verification_management',
        'mobile_otp_services',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def generate_mobile_o_t_p_using_p_o_s_t_1(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: GenerateMobileOTPRequest = ...,
):
    """
    Generate Mobile OTP to start registration
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/registration/mobile/resendOtp',
    description=""" Resend Mobile OTP in an existing transaction in case previous OTP is not received. """,
    tags=[
        'kyc_operations',
        'otp_generation_service',
        'otp_verification_management',
        'mobile_otp_services',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def resent_otp_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: ResendOTPRequest = ...,
):
    """
    Resend Mobile OTP for Health ID registration
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/registration/mobile/verifyOtp',
    description=""" Verify Mobile OTP in current registration transaction. """,
    tags=[
        'otp_verification_management',
        'mobile_otp_services',
        'authentication_process',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def verify_mobile_o_t_p_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: VerifyMobileRequest = ...,
):
    """
    Verify Mobile OTP sent as part of registration transaction.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/search/existsByHealthId',
    tags=['health_id_search_management', 'user_information_retrieval'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def search_user_by_userid_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: SearchByHealthIdRequest = ...,
):
    """
    Search a user by Health IDs.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/search/searchByHealthId',
    tags=['health_id_search_management', 'user_information_retrieval'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def search_user_by_account_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: SearchByHealthIdRequest = ...,
):
    """
    Search a user by Health ID Number.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/search/searchByMobile',
    tags=['user_information_retrieval', 'health_id_search_management'],
    security=[
        APIKeyHeader(name="Authorization"),
        APIKeyHeader(name="X-HIP-ID"),
    ],
)
def search_user_by_mobile_using_p_o_s_t(
    accept__language: Optional[str] = Header('en-US', alias='Accept-Language'),
    body: SearchByMobileRequest = ...,
):
    """
    Search users with a mobile number.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
